#!/usr/bin/env python3
# Generated by ref-inject/create
"""
generate.py — ref-inject テンプレートからリファレンス自動注入プラグインを生成する。

plugins/ref-inject/templates/* を plugins/{name}/ にコピーし、プレースホルダ
(__PLUGIN_NAME__ / __ENV_PREFIX__ / __LOG_TAG__ / __DEFAULT_TTL__ / __PLUGIN_DESCRIPTION__)
を置換して marketplace.json に登録する。テンプレートは {script_dir}/../templates から
読むため、このリポジトリ内でもインストール済みプラグインキャッシュからでも動く。

Usage:
  python generate.py --name foo-kit --description "..." \
      [--plugins-dir plugins] [--marketplace .claude-plugin/marketplace.json] \
      [--ttl 3600] [--force]
"""
from __future__ import annotations

# ── 標準ライブラリ ──────────────────────────────────────────
import argparse
import json
import re
import sys
from pathlib import Path
from typing import Final

# ── 定数 ────────────────────────────────────────────────────
# templates/{rel} は通常 plugin/{rel} に対応する。ここに載せたものだけ別の場所へ移す。
RELOCATE: Final[dict[str, str]] = {
    "plugin.json": ".claude-plugin/plugin.json",
}
# ここに挙げた拡張子だけプレースホルダ置換する。それ以外はそのままコピーする。
TEXT_SUFFIXES: Final[frozenset[str]] = frozenset(
    {".py", ".json", ".md", ".yaml", ".yml", ".j2", ".txt"}
)
PLUGIN_NAME_RE: Final[re.Pattern[str]] = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")

# ── 内部ヘルパー ────────────────────────────────────────────
def _env_prefix(name: str) -> str:
    return re.sub(r"[^0-9A-Za-z]+", "_", name).upper().strip("_")


def _substitute(text: str, repl: dict[str, str]) -> str:
    for key, val in repl.items():
        text = text.replace(key, val)
    return text


def _dest_rel(rel: str) -> str:
    return RELOCATE.get(rel, rel)


def _copy_templates(templates_dir: Path, target: Path, repl: dict[str, str]) -> list[str]:
    created: list[str] = []
    for src in sorted(templates_dir.rglob("*")):
        if src.is_dir():
            continue
        rel = src.relative_to(templates_dir).as_posix()
        dest = target / _dest_rel(rel)
        dest.parent.mkdir(parents=True, exist_ok=True)
        if src.suffix in TEXT_SUFFIXES:
            dest.write_text(_substitute(src.read_text(encoding="utf-8"), repl), encoding="utf-8")
        else:
            dest.write_bytes(src.read_bytes())
        created.append(str(dest))
    return created


def _register_marketplace(path: Path, name: str, description: str, plugins_dir: str) -> None:
    if not path.exists():
        print(f"warning: marketplace file {path} not found; skipping registration", file=sys.stderr)
        return
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        print(f"warning: cannot parse {path}: {e}; skipping registration", file=sys.stderr)
        return
    plugins = doc.setdefault("plugins", [])
    if any(isinstance(p, dict) and p.get("name") == name for p in plugins):
        print(f"note: {name} already in marketplace; left as-is", file=sys.stderr)
        return
    plugins.append({
        "name": name,
        "source": f"./{plugins_dir}/{name}",
        "description": description,
        "version": "0.1.0",
    })
    path.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


# ── メイン ──────────────────────────────────────────────────
def main(args: argparse.Namespace) -> int:
    name = args.name.strip()
    if not PLUGIN_NAME_RE.fullmatch(name):
        print(f"error: invalid plugin name {name!r} (use kebab-case)", file=sys.stderr)
        return 1

    templates_dir = Path(__file__).resolve().parents[1] / "templates"
    if not templates_dir.is_dir():
        print(f"error: templates dir not found at {templates_dir}", file=sys.stderr)
        return 1

    target = Path(args.plugins_dir) / name
    if target.exists() and not args.force:
        print(f"error: {target} already exists (use --force to overwrite)", file=sys.stderr)
        return 1

    repl = {
        "__PLUGIN_NAME__": name,
        "__ENV_PREFIX__": _env_prefix(name),
        "__LOG_TAG__": f"{name}-references-injection",
        "__DEFAULT_TTL__": str(args.ttl),
        "__PLUGIN_DESCRIPTION__": args.description,
    }

    created = _copy_templates(templates_dir, target, repl)
    _register_marketplace(Path(args.marketplace), name, args.description, args.plugins_dir)

    print(f"Generated plugin '{name}' at {target}")
    for path in created:
        print(f"  + {path}")
    print(f"Registered in {args.marketplace}")
    print("Next: fill references/ with real docs, update index.yaml + injection_rules.yaml.")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--name", required=True, help="plugin name (kebab-case)")
    parser.add_argument("--description", required=True, help="one-line plugin description")
    parser.add_argument("--plugins-dir", default="plugins", help="plugins directory (default: plugins)")
    parser.add_argument(
        "--marketplace",
        default=".claude-plugin/marketplace.json",
        help="marketplace.json path to register the plugin in",
    )
    parser.add_argument("--ttl", type=int, default=3600, help="default re-injection TTL in seconds")
    parser.add_argument("--force", action="store_true", help="overwrite if the plugin dir exists")
    return parser.parse_args()


if __name__ == "__main__":
    sys.exit(main(parse_args()))
