#!/usr/bin/env python3
# Generated by ref-inject/create
"""Generate a reference-auto-injection plugin from the ref-inject templates.

Copies plugins/ref-inject/templates/* into plugins/{name}/, substituting
placeholders (__PLUGIN_NAME__ / __ENV_PREFIX__ / __LOG_TAG__ / __DEFAULT_TTL__ /
__PLUGIN_DESCRIPTION__) and registering the plugin in marketplace.json.

Usage:
    python generate.py --name foo-kit --description "..." \
        --plugins-dir plugins --marketplace .claude-plugin/marketplace.json \
        [--ttl 3600] [--force]

The script reads its templates from {script_dir}/../templates, so it works both
inside this repo and from the installed plugin cache.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

# templates/{rel} -> plugin/{rel}, with a few relocations.
RELOCATE = {
    "plugin.json": ".claude-plugin/plugin.json",
}
TEXT_SUFFIXES = {".py", ".json", ".md", ".yaml", ".yml", ".j2", ".txt"}


def _env_prefix(name: str) -> str:
    return re.sub(r"[^0-9A-Za-z]+", "_", name).upper().strip("_")


def _substitute(text: str, repl: dict[str, str]) -> str:
    for key, val in repl.items():
        text = text.replace(key, val)
    return text


def _dest_rel(rel: pathlib.PurePosixPath) -> str:
    s = str(rel)
    return RELOCATE.get(s, s)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True, help="plugin name (kebab-case)")
    ap.add_argument("--description", required=True)
    ap.add_argument("--plugins-dir", default="plugins")
    ap.add_argument("--marketplace", default=".claude-plugin/marketplace.json")
    ap.add_argument("--ttl", type=int, default=3600)
    ap.add_argument("--force", action="store_true", help="overwrite if the plugin dir exists")
    args = ap.parse_args()

    name = args.name.strip()
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
        print(f"error: invalid plugin name {name!r} (use kebab-case)", file=sys.stderr)
        return 1

    templates_dir = pathlib.Path(__file__).resolve().parents[1] / "templates"
    if not templates_dir.is_dir():
        print(f"error: templates dir not found at {templates_dir}", file=sys.stderr)
        return 1

    target = pathlib.Path(args.plugins_dir) / name
    if target.exists() and not args.force:
        print(f"error: {target} already exists (use --force to overwrite)", file=sys.stderr)
        return 1

    repl = {
        "__PLUGIN_NAME__": name,
        "__ENV_PREFIX__": _env_prefix(name),
        "__LOG_TAG__": f"{name}-references-injection",
        "__DEFAULT_TTL__": str(args.ttl),
        "__PLUGIN_DESCRIPTION__": args.description,
    }

    created: list[str] = []
    for src in sorted(templates_dir.rglob("*")):
        if src.is_dir():
            continue
        rel = pathlib.PurePosixPath(src.relative_to(templates_dir).as_posix())
        dest = target / _dest_rel(rel)
        dest.parent.mkdir(parents=True, exist_ok=True)
        if src.suffix in TEXT_SUFFIXES:
            dest.write_text(_substitute(src.read_text(encoding="utf-8"), repl), encoding="utf-8")
        else:
            dest.write_bytes(src.read_bytes())
        created.append(str(dest))

    _register_marketplace(pathlib.Path(args.marketplace), name, args.description, args.plugins_dir)

    print(f"Generated plugin '{name}' at {target}")
    for c in created:
        print(f"  + {c}")
    print(f"Registered in {args.marketplace}")
    print("Next: fill references/ with real docs, update index.yaml + injection_rules.yaml.")
    return 0


def _register_marketplace(path: pathlib.Path, name: str, description: str, plugins_dir: str) -> None:
    if not path.exists():
        print(f"warning: marketplace file {path} not found; skipping registration", file=sys.stderr)
        return
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"warning: cannot parse {path}: {e}; skipping registration", file=sys.stderr)
        return
    plugins = doc.setdefault("plugins", [])
    if any(isinstance(p, dict) and p.get("name") == name for p in plugins):
        print(f"note: {name} already in marketplace; left as-is", file=sys.stderr)
        return
    plugins.append({
        "name": name,
        "source": f"./{plugins_dir}/{name}",
        "description": description,
        "version": "0.1.0",
    })
    path.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
