# Generated by claude-kit/hook-creator v3.24.1
"""session-kit context-generation marker hook.

2 つのイベントを処理する:

- PreCompact   : セッションマーカー `/tmp/claude-session-ctx-gen-{session_id}` を touch する。
                 mtime = そのセッションで最後にコンテキストがリセット (compact) された時刻。
                 他プラグイン (py-kit / next-kit) の注入フックはこの mtime と自分の注入トークンの
                 mtime を比較し、マーカーが新しければ再注入する。
- SessionStart : 古い一時ファイルを掃除する (TTL = 1 日)。掃除対象は
                 `claude-session-ctx-gen-*` (セッションマーカー) と
                 `*-references-injection-*` (py-kit / next-kit の注入トークン)。

`/clear` のマーカーバンプは行わない: `/clear` は session_id 自体を変えるため、新セッションは
新しい session_id で自然に再注入される (旧トークンは別 session_id なので無関係)。session_id が
同じまま残るのは `/compact` だけなので、マーカーは PreCompact でのみ更新すればよい。

掃除は SessionStart で 1 回だけ走る (毎プロンプトではない) ため、フラグ等のガードは不要。
現在アクティブなセッションのトークンは新しい (< 1 日) ので TTL では消えない。並行セッションも同様。
"""
from __future__ import annotations

import json
import pathlib
import sys
import tempfile
import time

# 掃除対象の glob パターンと TTL
_TTL_SECONDS = 24 * 60 * 60  # 1 日
_CLEANUP_GLOBS = (
    "claude-session-ctx-gen-*",      # セッションマーカー (session-kit)
    "*-references-injection-*",      # 注入トークン (py-kit / next-kit / 将来の *-kit)
)


def _touch_marker(session_id: str) -> None:
    marker = pathlib.Path(tempfile.gettempdir()) / f"claude-session-ctx-gen-{session_id}"
    try:
        marker.touch()
    except OSError:
        pass


def _cleanup_stale() -> None:
    tmp = pathlib.Path(tempfile.gettempdir())
    cutoff = time.time() - _TTL_SECONDS
    for pattern in _CLEANUP_GLOBS:
        for p in tmp.glob(pattern):
            try:
                if p.is_file() and p.stat().st_mtime < cutoff:
                    p.unlink()
            except OSError:
                pass


def main() -> int:
    try:
        data = json.loads(sys.stdin.read())
    except Exception:
        return 0

    event = data.get("hook_event_name", "")
    if event == "PreCompact":
        _touch_marker(data.get("session_id", "default"))
    elif event == "SessionStart":
        _cleanup_stale()
    return 0


if __name__ == "__main__":
    sys.exit(main())
