# Generated by claude-kit/hook-creator v3.24.1
"""session-kit context-generation marker hook.

PreCompact / SessionStart(source=clear) で発火し、コンテキストがリセットされたことを
表すマーカーファイル `/tmp/claude-session-ctx-gen-{session_id}` を touch（mtime 更新）する。

他プラグイン（py-kit / next-kit など）の reference 自動注入フックは、自分の per-file
トークンの mtime とこのマーカーの mtime を比較し、マーカーの方が新しければ
「直近の注入後に compact / clear が起きた＝注入内容がコンテキストから消えた」と判断して
再注入する。マーカーが存在しない場合（session-kit 未インストール）は once-per-session に
フォールバックする。

連携はこのファイルパス規約のみ。他プラグインはこのスクリプトを呼ばず、マーカーファイルを
stat するだけ。

マーカーを更新するイベント:
    - PreCompact          : 常に（compact 直前）
    - SessionStart(clear) : /clear 時のみ（startup / resume では更新しない）

startup を除外する理由: 新規セッションは session_id が新しく、消すべき旧トークンが無い。
resume を除外する理由: 会話が復元されるため注入済み内容もコンテキストに戻り再注入が不要。
"""
from __future__ import annotations

import json
import pathlib
import sys
import tempfile


def main() -> int:
    try:
        data = json.loads(sys.stdin.read())
    except Exception:
        return 0

    event = data.get("hook_event_name", "")
    session_id = data.get("session_id", "default")

    should_touch = False
    if event == "PreCompact":
        should_touch = True
    elif event == "SessionStart":
        should_touch = data.get("source") == "clear"

    if not should_touch:
        return 0

    marker = pathlib.Path(tempfile.gettempdir()) / f"claude-session-ctx-gen-{session_id}"
    try:
        marker.touch()
    except OSError:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
