# Generated by claude-kit/hook-creator v3.24.1
"""session-kit injection-token garbage collector.

他プラグイン (py-kit / next-kit など) が `~/.claude/tokens/{plugin}/{session_id}-{patternhash}`
に作る「注入トークン」の寿命を管理する。注入トークンは「この injection_rules パターンの
reference はこのターンで注入済み」の印 (空ファイル)。プラグインごとにサブフォルダを分ける。

2 つのイベントを処理する:

- UserPromptSubmit : **現セッションの**注入トークンを削除する (全プラグインのフォルダ横断)。
                     これにより注入キャッシュは「会話ターン単位」になる。長いセッションだと
                     早い段階で注入した内容がコンテキストの下の方に埋もれてしまうため、ユーザーが
                     新しいプロンプトを出すたびにトークンを消し、次にそのパターンのファイルを
                     触ったら再注入する。
- SessionStart    : 古い注入トークン (TTL = 1 日) を掃除する。トークンはセッションごとに
                     溜まり続けるため。

`/clear` / `/compact` は個別に扱わない: `/clear` は session_id が変わるので新セッションが
自然に再注入する。`/compact` 後も次の UserPromptSubmit でトークンが消えて再注入される。

利用側 (py-kit / next-kit) はこのプラグインを一切知らない。自分のトークンを作って存在チェック
するだけで、session-kit が外部から削除する。session-kit 未インストール時はトークンが消えない
だけ (セッション単位の once-per-pattern 挙動)。

連携はファイルパス規約 (`~/.claude/tokens/{plugin}/{session_id}-*`) のみ。session-kit は
このディレクトリを glob するだけで他プラグインのコードは呼ばない。

注意: WSL と Windows で `Path.home()` の解決先が変わりうるが、切替頻度は低く、別ロケーションに
なっても最悪は再注入が走るだけなので許容する。
"""
from __future__ import annotations

import json
import pathlib
import sys
import time

_TTL_SECONDS = 24 * 60 * 60  # 1 日


def _tokens_dir() -> pathlib.Path:
    return pathlib.Path.home() / ".claude" / "tokens"


def _delete_session_tokens(session_id: str) -> None:
    """現セッションの注入トークンをすべて削除 (会話ターンごとのリセット、全プラグイン横断)。"""
    base = _tokens_dir()
    if not base.exists():
        return
    for p in base.glob(f"*/{session_id}-*"):
        try:
            p.unlink()
        except OSError:
            pass


def _gc_stale_tokens() -> None:
    """1 日以上前の注入トークンを掃除 (溜まり防止、全プラグイン横断)。"""
    base = _tokens_dir()
    if not base.exists():
        return
    cutoff = time.time() - _TTL_SECONDS
    for p in base.glob("*/*"):
        try:
            if p.is_file() and p.stat().st_mtime < cutoff:
                p.unlink()
        except OSError:
            pass


def main() -> int:
    try:
        data = json.loads(sys.stdin.read())
    except Exception:
        return 0

    event = data.get("hook_event_name", "")
    if event == "UserPromptSubmit":
        _delete_session_tokens(data.get("session_id", "default"))
    elif event == "SessionStart":
        _gc_stale_tokens()
    return 0


if __name__ == "__main__":
    sys.exit(main())
