# Generated by claude-kit/hook-creator v3.24.1
"""session-kit injection-token garbage collector.

他プラグイン (py-kit / next-kit など) が作る「注入トークン」
`/tmp/*-references-injection-{session_id}-{patternhash}` の寿命を管理する。
注入トークンは「このパターンの reference はこのターンで注入済み」の印 (空ファイル)。

2 つのイベントを処理する:

- UserPromptSubmit : **現セッションの**注入トークンを削除する。これにより注入キャッシュは
                     「会話ターン単位」になる。長いセッションだと早い段階で注入した内容が
                     コンテキストの下の方に埋もれてしまうため、ユーザーが新しいプロンプトを
                     出すたびにトークンを消し、次にそのパターンのファイルを触ったら再注入する。
- SessionStart    : 古い注入トークン (TTL = 1 日) を掃除する。トークンはセッションごとに
                     溜まり続けるため。

`/clear` / `/compact` は個別に扱わない: `/clear` は session_id が変わるので新セッションが
自然に再注入する。`/compact` 後も次の UserPromptSubmit でトークンが消えて再注入される。

利用側 (py-kit / next-kit) はこのプラグインを一切知らない。自分のトークンを作って存在チェック
するだけで、session-kit が外部から削除する。session-kit 未インストール時はトークンが消えない
だけ (セッション単位の once-per-pattern 挙動)。

連携はファイル名規約のみ (session-kit は /tmp を glob するだけで他プラグインのコードは
呼ばない)。
"""
from __future__ import annotations

import json
import pathlib
import sys
import tempfile
import time

_TTL_SECONDS = 24 * 60 * 60  # 1 日
_TOKEN_GLOB = "*-references-injection-*"  # py-kit / next-kit / 将来の *-kit


def _delete_session_tokens(session_id: str) -> None:
    """現セッションの注入トークンをすべて削除 (会話ターンごとのリセット)。"""
    tmp = pathlib.Path(tempfile.gettempdir())
    for p in tmp.glob(f"*-references-injection-{session_id}-*"):
        try:
            p.unlink()
        except OSError:
            pass


def _gc_stale_tokens() -> None:
    """1 日以上前の注入トークンを掃除 (溜まり防止)。"""
    tmp = pathlib.Path(tempfile.gettempdir())
    cutoff = time.time() - _TTL_SECONDS
    for p in tmp.glob(_TOKEN_GLOB):
        try:
            if p.is_file() and p.stat().st_mtime < cutoff:
                p.unlink()
        except OSError:
            pass


def main() -> int:
    try:
        data = json.loads(sys.stdin.read())
    except Exception:
        return 0

    event = data.get("hook_event_name", "")
    if event == "UserPromptSubmit":
        _delete_session_tokens(data.get("session_id", "default"))
    elif event == "SessionStart":
        _gc_stale_tokens()
    return 0


if __name__ == "__main__":
    sys.exit(main())
