# Generated by claude-kit/hook-creator v3.24.1
"""py-kit references auto-injection hook.

PreToolUse(Edit | Write | MultiEdit) で発火し、編集対象ファイルパスを
references/index.yaml の injection_rules と照合する。マッチした reference の本文を
Jinja2 で整形して `decision: block` の reason に注入する。

同一ファイルへの 2 回目以降の編集は、セッション + ファイルハッシュ単位のトークンで
スキップする (1 セッション 1 ファイル 1 回だけブロック)。

依存:
    - PyYAML  (uv/pip install pyyaml)
    - Jinja2  (uv/pip install jinja2)
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import re
import sys
import tempfile


def _eprint(msg: str) -> None:
    """stderr に出力（フックの transcript に残り、Claude へは渡さない）。"""
    sys.stderr.write(f"[py-references-injection] {msg}\n")


def _plugin_root() -> pathlib.Path:
    """plugin ルート (plugins/py-kit) を返す。

    Claude Code は hook 起動時に CLAUDE_PLUGIN_ROOT を設定するが、
    フォールバックとしてスクリプト位置の 2 階層上 (hooks/ の親) を使う。
    """
    env = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        return pathlib.Path(env)
    return pathlib.Path(__file__).resolve().parents[1]


# --------------------------------------------------------------------------- #
# glob → regex  (** = 任意階層、* = 単一階層内、? = 1 文字)
# --------------------------------------------------------------------------- #
def _glob_to_regex(pattern: str) -> re.Pattern[str]:
    parts: list[str] = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "*" and i + 1 < len(pattern) and pattern[i + 1] == "*":
            parts.append(".*")
            i += 2
            if i < len(pattern) and pattern[i] == "/":
                i += 1
        elif c == "*":
            parts.append("[^/]*")
            i += 1
        elif c == "?":
            parts.append("[^/]")
            i += 1
        elif c in "[]":
            parts.append(c)
            i += 1
        elif c == "{":
            parts.append("(?:")
            i += 1
        elif c == "}":
            parts.append(")")
            i += 1
        elif c == ",":
            parts.append("|")
            i += 1
        else:
            parts.append(re.escape(c))
            i += 1
    return re.compile("^" + "".join(parts) + "$")


def _match_any(pattern: str, candidates: list[str]) -> bool:
    rx = _glob_to_regex(pattern)
    return any(rx.match(c) for c in candidates)


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main() -> int:
    # 依存チェック (失敗時は静かに pass)
    try:
        import yaml
        from jinja2 import Environment, FileSystemLoader, StrictUndefined
    except ImportError as e:
        _eprint(f"missing dependency: {e}. install with: uv add --dev pyyaml jinja2")
        return 0

    try:
        data = json.loads(sys.stdin.read())
    except Exception as e:
        _eprint(f"stdin parse error: {e}")
        return 0

    tool_name = data.get("tool_name", "")
    if tool_name not in ("Edit", "Write", "MultiEdit"):
        return 0

    file_path: str = data.get("tool_input", {}).get("file_path", "") or ""
    if not file_path:
        return 0

    plugin_root = _plugin_root()
    refs_dir = plugin_root / "references"
    index_yaml = refs_dir / "index.yaml"
    if not index_yaml.exists():
        _eprint(f"index.yaml not found at {index_yaml}")
        return 0

    try:
        idx = yaml.safe_load(index_yaml.read_text(encoding="utf-8")) or {}
    except Exception as e:
        _eprint(f"index.yaml parse error: {e}")
        return 0

    # ----- file_path の候補を作る (絶対パス + プロジェクトルートからの相対パス) -----
    norm: list[str] = [file_path.replace("\\", "/")]
    project_dir = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    try:
        rel = pathlib.Path(file_path).resolve().relative_to(pathlib.Path(project_dir).resolve())
        norm.append(str(rel).replace("\\", "/"))
    except (ValueError, OSError):
        pass

    # ----- injection_rules を照合 -----
    required: list[str] = []
    optional: list[str] = []
    for rule in idx.get("injection_rules") or []:
        pat = rule.get("pattern", "")
        if not pat:
            continue
        if _match_any(pat, norm):
            required.extend(rule.get("required") or [])
            optional.extend(rule.get("optional") or [])

    # 重複を除く (順序は保持)
    def _dedup(xs: list[str]) -> list[str]:
        seen: set[str] = set()
        out: list[str] = []
        for x in xs:
            if x not in seen:
                seen.add(x)
                out.append(x)
        return out

    required = _dedup(required)
    optional = _dedup([p for p in optional if p not in set(required)])

    if not required and not optional:
        return 0

    # ----- セッション + ファイル単位のトークン (1 ファイル 1 回だけ block) -----
    session_id: str = data.get("session_id", "default")
    file_hash = hashlib.sha1(file_path.encode("utf-8")).hexdigest()[:12]
    token = pathlib.Path(tempfile.gettempdir()) / f"py-references-injection-{session_id}-{file_hash}"
    if token.exists():
        return 0
    token.touch()

    # ----- reference 本文 + description を集める -----
    descriptions: dict[str, str] = {
        (r.get("path") or ""): (r.get("description") or "")
        for r in (idx.get("references") or [])
    }

    def _read_ref(rel_path: str) -> dict[str, str]:
        body = ""
        full = refs_dir / rel_path
        if full.exists():
            try:
                body = full.read_text(encoding="utf-8")
            except Exception as e:
                _eprint(f"read failed {full}: {e}")
        return {
            "path": rel_path,
            "description": descriptions.get(rel_path, ""),
            "body": body,
        }

    required_data = [_read_ref(p) for p in required]
    optional_data = [_read_ref(p) for p in optional]

    # ----- Jinja2 render -----
    tmpl_dir = plugin_root / "hooks" / "templates"
    env = Environment(
        loader=FileSystemLoader(str(tmpl_dir)),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    try:
        tmpl = env.get_template("injection.md.j2")
        reason = tmpl.render(
            file_path=file_path,
            required=required_data,
            optional=optional_data,
        )
    except Exception as e:
        _eprint(f"template render error: {e}")
        # フォールバック: 最小限の本文だけ流す
        lines = [f"# py-kit references (template error: {e})", "", f"target: {file_path}", ""]
        for r in required_data:
            lines.append(f"## {r['path']}")
            lines.append("")
            lines.append(r["body"])
            lines.append("")
        reason = "\n".join(lines)

    sys.stdout.buffer.write(
        json.dumps({"decision": "block", "reason": reason}, ensure_ascii=False).encode("utf-8")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
