# Generated by claude-kit/hook-creator v3.24.1
"""py-kit references auto-injection hook.

PreToolUse(Edit | Write | MultiEdit | Read) で発火し、対象ファイルパスを
references/injection_rules.yaml の rules と照合する。マッチした reference の
path と description を Jinja2 で整形して `decision: block` の reason に注入する。
本文は注入せず、Claude Code が `Read` で必要なファイルを読む設計。
Read は issue-scan などの読み取り経路でも reference を入手できるよう許可している。

description は references/index.yaml（英語）から path → description として取得する。
日本語が必要な場合は環境変数 PY_KIT_INJECTION_LANG=jp を設定すれば
index.jp.yaml + injection.jp.md.j2 を使う。

同一ファイルへの 2 回目以降の編集は、セッション + ファイルハッシュ単位のトークンで
スキップする (1 セッション 1 ファイル 1 回だけブロック)。

依存:
    - PyYAML  (uv/pip install pyyaml)
    - Jinja2  (uv/pip install jinja2)
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import re
import sys


def _eprint(msg: str) -> None:
    """stderr に出力（フックの transcript に残り、Claude へは渡さない）。"""
    sys.stderr.write(f"[py-references-injection] {msg}\n")


def _plugin_root() -> pathlib.Path:
    """plugin ルート (plugins/py-kit) を返す。

    Claude Code は hook 起動時に CLAUDE_PLUGIN_ROOT を設定するが、
    フォールバックとしてスクリプト位置の 2 階層上 (hooks/ の親) を使う。
    """
    env = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        return pathlib.Path(env)
    return pathlib.Path(__file__).resolve().parents[1]


# --------------------------------------------------------------------------- #
# glob → regex  (** = 任意階層、* = 単一階層内、? = 1 文字)
# --------------------------------------------------------------------------- #
def _glob_to_regex(pattern: str) -> re.Pattern[str]:
    parts: list[str] = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "*" and i + 1 < len(pattern) and pattern[i + 1] == "*":
            parts.append(".*")
            i += 2
            if i < len(pattern) and pattern[i] == "/":
                i += 1
        elif c == "*":
            parts.append("[^/]*")
            i += 1
        elif c == "?":
            parts.append("[^/]")
            i += 1
        elif c in "[]":
            parts.append(c)
            i += 1
        elif c == "{":
            parts.append("(?:")
            i += 1
        elif c == "}":
            parts.append(")")
            i += 1
        elif c == ",":
            parts.append("|")
            i += 1
        else:
            parts.append(re.escape(c))
            i += 1
    return re.compile("^" + "".join(parts) + "$")


def _match_any(pattern: str, candidates: list[str]) -> bool:
    rx = _glob_to_regex(pattern)
    return any(rx.match(c) for c in candidates)


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main() -> int:
    # 依存チェック (失敗時は静かに pass)
    try:
        import yaml
        from jinja2 import Environment, FileSystemLoader, StrictUndefined
    except ImportError as e:
        _eprint(f"missing dependency: {e}. install with: uv add --dev pyyaml jinja2")
        return 0

    try:
        data = json.loads(sys.stdin.read())
    except Exception as e:
        _eprint(f"stdin parse error: {e}")
        return 0

    tool_name = data.get("tool_name", "")
    if tool_name not in ("Edit", "Write", "MultiEdit", "Read"):
        return 0

    file_path: str = data.get("tool_input", {}).get("file_path", "") or ""
    if not file_path:
        return 0

    plugin_root = _plugin_root()
    refs_dir = plugin_root / "references"

    # 言語選択: 環境変数 PY_KIT_INJECTION_LANG=jp で日本語版
    lang = os.environ.get("PY_KIT_INJECTION_LANG", "en").lower()
    index_filename = "index.jp.yaml" if lang == "jp" else "index.yaml"
    template_filename = "injection.jp.md.j2" if lang == "jp" else "injection.md.j2"

    rules_yaml = refs_dir / "injection_rules.yaml"
    index_yaml = refs_dir / index_filename
    if not rules_yaml.exists():
        _eprint(f"injection_rules.yaml not found at {rules_yaml}")
        return 0
    if not index_yaml.exists():
        _eprint(f"{index_filename} not found at {index_yaml}")
        return 0

    # ----- injection_rules.yaml をロード -----
    try:
        rules_doc = yaml.safe_load(rules_yaml.read_text(encoding="utf-8")) or {}
    except Exception as e:
        _eprint(f"injection_rules.yaml parse error: {e}")
        return 0
    rules = rules_doc.get("rules") or []

    # ----- index.yaml から path → description -----
    descriptions: dict[str, str] = {}
    try:
        idx_doc = yaml.safe_load(index_yaml.read_text(encoding="utf-8")) or {}
        for ref in idx_doc.get("references") or []:
            p = ref.get("path")
            d = ref.get("description") or ""
            if p:
                descriptions[p] = d
    except Exception as e:
        _eprint(f"{index_filename} parse error: {e}")

    # ----- file_path の候補を作る (絶対パス + プロジェクトルートからの相対パス) -----
    norm: list[str] = [file_path.replace("\\", "/")]
    project_dir = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    try:
        rel = pathlib.Path(file_path).resolve().relative_to(pathlib.Path(project_dir).resolve())
        norm.append(str(rel).replace("\\", "/"))
    except (ValueError, OSError):
        pass

    # 重複を除く (順序は保持)
    def _dedup(xs: list[str]) -> list[str]:
        seen: set[str] = set()
        out: list[str] = []
        for x in xs:
            if x not in seen:
                seen.add(x)
                out.append(x)
        return out

    # ----- injection_rules を照合し、パターン単位の注入トークンで未注入のものだけ集める -----
    # トークンはファイル単位ではなく injection_rules の「パターン単位」。同じパターンにマッチ
    # する別ファイルを開いても、そのパターンの reference は再注入しない。ファイルが複数パターン
    # にマッチする場合は、未注入 (トークンが無い) パターンの reference のみ注入する。
    # キャッシュはセッション単位 (once-per-pattern): 同一パターンの reference はそのセッションで
    # 一度だけ注入する。トークンは ~/.claude/tokens/py-kit/{session_id}-{patternhash} に置く
    # (空ファイルとして溜まるが自動削除はしない)。
    session_id: str = data.get("session_id", "default")
    token_dir = pathlib.Path.home() / ".claude" / "tokens" / "py-kit"
    required: list[str] = []
    optional: list[str] = []
    new_pattern_tokens: list[pathlib.Path] = []
    for rule in rules:
        pat = rule.get("pattern", "")
        if not pat or not _match_any(pat, norm):
            continue
        pat_hash = hashlib.sha1(pat.encode("utf-8")).hexdigest()[:12]
        token = token_dir / f"{session_id}-{pat_hash}"
        if token.exists():
            continue  # このパターンの reference はこのセッションで注入済み → スキップ
        new_pattern_tokens.append(token)
        required.extend(rule.get("required") or [])
        optional.extend(rule.get("optional") or [])

    required = _dedup(required)
    optional = _dedup([p for p in optional if p not in set(required)])

    if not required and not optional:
        return 0  # マッチ無し、または全マッチパターンが注入済み

    # 注入するパターンのトークンを作成 (セッション内の重複注入を防ぐ)
    token_dir.mkdir(parents=True, exist_ok=True)
    for token in new_pattern_tokens:
        token.touch()

    # ----- reference の path (絶対) + description を集める -----
    # 注入テキスト内では ${CLAUDE_PLUGIN_ROOT} は展開されないため、Claude が Read できる
    # 絶対パスを出す (1行参照パターン)。
    def _read_ref(rel_path: str) -> dict[str, str]:
        return {
            "path": rel_path,
            "abs_path": (refs_dir / rel_path).as_posix(),
            "description": descriptions.get(rel_path, ""),
        }

    required_data = [_read_ref(p) for p in required]
    optional_data = [_read_ref(p) for p in optional]

    # ----- Jinja2 render -----
    tmpl_dir = plugin_root / "hooks" / "templates"
    env = Environment(
        loader=FileSystemLoader(str(tmpl_dir)),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    try:
        tmpl = env.get_template(template_filename)
        reason = tmpl.render(
            file_path=file_path,
            required=required_data,
            optional=optional_data,
        )
    except Exception as e:
        _eprint(f"template render error ({template_filename}): {e}")
        lines = [f"# py-kit references (template error: {e})", "", f"target: {file_path}", ""]
        for r in required_data:
            lines.append(f"- {r['abs_path']} — {r['description']}")
        reason = "\n".join(lines)

    sys.stdout.buffer.write(
        json.dumps({"decision": "block", "reason": reason}, ensure_ascii=False).encode("utf-8")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
