# Generated by refs-inject-kit/inject-references-hook v1.0.0
"""refs-inject-kit — generic references auto-injection hook.

PreToolUse(Edit | Write | MultiEdit) で発火し、**インストール済みプラグインの中で
`references/injection_rules.yaml` を持つもの** を自動検出し、それぞれの rules を
編集対象ファイルパスと glob 照合する。マッチした reference の本文を、各プラグインの
`references/index.yaml` から取得した description と一緒に Jinja2 で整形し、
`decision: block` の reason に注入する。

各プラグイン側 (e.g. py-kit / next-kit) は以下のファイルだけを持てばよい:
- `references/injection_rules.yaml`: pattern → required/optional reference
- `references/index.yaml`: 英語 description (フックが parse)
- `references/index.jp.yaml`: 日本語ミラー (PY_KIT_INJECTION_LANG=jp で参照)
- `references/**/*.md`: 本文

同一ファイルへの 2 回目以降の編集は、セッション + ファイルハッシュ単位のトークンで
スキップする (1 セッション 1 ファイル 1 回だけブロック)。

検出対象パス (環境ごとに該当するものを走査):
- `${HOME}/.claude/plugins/cache/*/*/*/references/injection_rules.yaml`
- `${CLAUDE_PROJECT_DIR}/plugins/*/references/injection_rules.yaml` (marketplace development 時)
- `${REFS_INJECT_KIT_EXTRA_PATHS}` 環境変数で `:` 区切り追加可能

依存:
    - PyYAML  (pip install pyyaml)
    - Jinja2  (pip install jinja2)
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import re
import sys
import tempfile


def _eprint(msg: str) -> None:
    """stderr に出力 (フックの transcript に残り、Claude へは渡さない)。"""
    sys.stderr.write(f"[refs-inject-kit] {msg}\n")


def _plugin_root() -> pathlib.Path:
    """refs-inject-kit プラグインの root を返す (Jinja2 テンプレ置き場)。"""
    env = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        return pathlib.Path(env)
    return pathlib.Path(__file__).resolve().parents[1]


# --------------------------------------------------------------------------- #
# glob → regex  (** = 任意階層、* = 単一階層内、? = 1 文字)
# --------------------------------------------------------------------------- #
def _glob_to_regex(pattern: str) -> re.Pattern[str]:
    parts: list[str] = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "*" and i + 1 < len(pattern) and pattern[i + 1] == "*":
            parts.append(".*")
            i += 2
            if i < len(pattern) and pattern[i] == "/":
                i += 1
        elif c == "*":
            parts.append("[^/]*")
            i += 1
        elif c == "?":
            parts.append("[^/]")
            i += 1
        elif c in "[]":
            parts.append(c)
            i += 1
        elif c == "{":
            parts.append("(?:")
            i += 1
        elif c == "}":
            parts.append(")")
            i += 1
        elif c == ",":
            parts.append("|")
            i += 1
        else:
            parts.append(re.escape(c))
            i += 1
    return re.compile("^" + "".join(parts) + "$")


def _match_any(pattern: str, candidates: list[str]) -> bool:
    rx = _glob_to_regex(pattern)
    return any(rx.match(c) for c in candidates)


# --------------------------------------------------------------------------- #
# プラグイン検出
# --------------------------------------------------------------------------- #
def _find_references_dirs() -> list[pathlib.Path]:
    """`references/injection_rules.yaml` を持つすべてのプラグイン references/ を返す。

    複数の探索場所を走査:
    - `${HOME}/.claude/plugins/cache/*/*/*/references/injection_rules.yaml` (インストール済み)
    - `${CLAUDE_PROJECT_DIR}/plugins/*/references/injection_rules.yaml` (marketplace dev)
    - `${REFS_INJECT_KIT_EXTRA_PATHS}` (`:` 区切りで追加プラグインルート)
    """
    found: list[pathlib.Path] = []
    seen: set[str] = set()

    def _add(p: pathlib.Path) -> None:
        try:
            r = p.resolve()
        except OSError:
            return
        key = str(r)
        if key in seen:
            return
        seen.add(key)
        found.append(r)

    # インストール済みプラグイン (`~/.claude/plugins/cache/{owner}/{name}/{version}/`)
    home_cache = pathlib.Path.home() / ".claude" / "plugins" / "cache"
    if home_cache.exists():
        for rules_yaml in home_cache.glob("*/*/*/references/injection_rules.yaml"):
            _add(rules_yaml.parent)

    # marketplace 開発時: ${CLAUDE_PROJECT_DIR}/plugins/{name}/references/...
    project_dir = os.environ.get("CLAUDE_PROJECT_DIR")
    if project_dir:
        proj = pathlib.Path(project_dir)
        for rules_yaml in proj.glob("plugins/*/references/injection_rules.yaml"):
            _add(rules_yaml.parent)

    # 追加パス (環境変数、`:` 区切り、各エントリは plugin root)
    extra = os.environ.get("REFS_INJECT_KIT_EXTRA_PATHS", "")
    for entry in extra.split(os.pathsep):
        if not entry.strip():
            continue
        candidate = pathlib.Path(entry.strip()) / "references" / "injection_rules.yaml"
        if candidate.exists():
            _add(candidate.parent)

    return found


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main() -> int:
    # 依存チェック (失敗時は静かに pass)
    try:
        import yaml
        from jinja2 import Environment, FileSystemLoader, StrictUndefined
    except ImportError as e:
        _eprint(f"missing dependency: {e}. install with: pip install pyyaml jinja2")
        return 0

    try:
        data = json.loads(sys.stdin.read())
    except Exception as e:
        _eprint(f"stdin parse error: {e}")
        return 0

    tool_name = data.get("tool_name", "")
    if tool_name not in ("Edit", "Write", "MultiEdit"):
        return 0

    file_path: str = data.get("tool_input", {}).get("file_path", "") or ""
    if not file_path:
        return 0

    # 言語選択 (環境変数で切替、デフォルト英語)
    lang = os.environ.get("REFS_INJECT_KIT_LANG", "en").lower()
    index_filename = "index.jp.yaml" if lang == "jp" else "index.yaml"
    template_filename = "injection.jp.md.j2" if lang == "jp" else "injection.md.j2"

    # ----- ファイルパスの候補 -----
    norm: list[str] = [file_path.replace("\\", "/")]
    project_dir = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    try:
        rel = pathlib.Path(file_path).resolve().relative_to(pathlib.Path(project_dir).resolve())
        norm.append(str(rel).replace("\\", "/"))
    except (ValueError, OSError):
        pass

    # ----- プラグイン検出 + 各プラグインで rule 照合 -----
    refs_dirs = _find_references_dirs()
    if not refs_dirs:
        return 0

    # plugin ごとに matched references を集める
    # 構造: [{ "plugin": "py-kit", "refs_dir": Path, "required": [...], "optional": [...] }]
    plugin_matches: list[dict[str, object]] = []

    for refs_dir in refs_dirs:
        rules_yaml = refs_dir / "injection_rules.yaml"
        try:
            rules_doc = yaml.safe_load(rules_yaml.read_text(encoding="utf-8")) or {}
        except Exception as e:
            _eprint(f"{rules_yaml} parse error: {e}")
            continue
        rules = rules_doc.get("rules") or []

        required: list[str] = []
        optional: list[str] = []
        for rule in rules:
            pat = rule.get("pattern", "")
            if not pat:
                continue
            if _match_any(pat, norm):
                required.extend(rule.get("required") or [])
                optional.extend(rule.get("optional") or [])

        def _dedup(xs: list[str]) -> list[str]:
            seen_: set[str] = set()
            out: list[str] = []
            for x in xs:
                if x not in seen_:
                    seen_.add(x)
                    out.append(x)
            return out

        required = _dedup(required)
        optional = _dedup([p for p in optional if p not in set(required)])
        if not required and not optional:
            continue

        # plugin 名は references の 2 階層上 (plugins/{name}/references/)
        plugin_name = refs_dir.parent.name
        plugin_matches.append({
            "plugin": plugin_name,
            "refs_dir": refs_dir,
            "required": required,
            "optional": optional,
        })

    if not plugin_matches:
        return 0

    # ----- セッション + ファイル単位のトークン (1 ファイル 1 回だけ block) -----
    session_id: str = data.get("session_id", "default")
    file_hash = hashlib.sha1(file_path.encode("utf-8")).hexdigest()[:12]
    token = pathlib.Path(tempfile.gettempdir()) / f"refs-inject-kit-{session_id}-{file_hash}"
    if token.exists():
        return 0
    token.touch()

    # ----- 各 plugin の reference 本文 + description を集める -----
    def _read_ref(refs_dir: pathlib.Path, rel_path: str, descriptions: dict[str, str]) -> dict[str, str]:
        body = ""
        full = refs_dir / rel_path
        if full.exists():
            try:
                body = full.read_text(encoding="utf-8")
            except Exception as e:
                _eprint(f"read failed {full}: {e}")
        return {
            "path": rel_path,
            "description": descriptions.get(rel_path, ""),
            "body": body,
        }

    for m in plugin_matches:
        refs_dir = m["refs_dir"]  # type: ignore[assignment]
        index_yaml = refs_dir / index_filename
        descriptions: dict[str, str] = {}
        if index_yaml.exists():
            try:
                idx_doc = yaml.safe_load(index_yaml.read_text(encoding="utf-8")) or {}
                for ref in idx_doc.get("references") or []:
                    p = ref.get("path")
                    d = ref.get("description") or ""
                    if p:
                        descriptions[p] = d
            except Exception as e:
                _eprint(f"{index_yaml} parse error: {e}")
        m["required_data"] = [_read_ref(refs_dir, p, descriptions) for p in m["required"]]  # type: ignore[arg-type]
        m["optional_data"] = [_read_ref(refs_dir, p, descriptions) for p in m["optional"]]  # type: ignore[arg-type]

    # ----- Jinja2 render -----
    tmpl_dir = _plugin_root() / "hooks" / "templates"
    env = Environment(
        loader=FileSystemLoader(str(tmpl_dir)),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    try:
        tmpl = env.get_template(template_filename)
        reason = tmpl.render(
            file_path=file_path,
            plugins=plugin_matches,
        )
    except Exception as e:
        _eprint(f"template render error ({template_filename}): {e}")
        # フォールバック: 最小限の本文だけ流す
        lines = [f"# refs-inject-kit (template error: {e})", "", f"target: {file_path}", ""]
        for m in plugin_matches:
            lines.append(f"## from {m['plugin']}")
            for r in m.get("required_data") or []:
                lines.append(f"### {r['path']}")
                lines.append("")
                lines.append(r["body"])
                lines.append("")
        reason = "\n".join(lines)

    sys.stdout.buffer.write(
        json.dumps({"decision": "block", "reason": reason}, ensure_ascii=False).encode("utf-8")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
