# Generated by refs-inject-kit/inject-references-hook v1.1.0
"""refs-inject-kit — generic references auto-injection hook.

PreToolUse(Edit | Write | MultiEdit) で発火する。

設計 (v1.1.0 で集約版に変更):
- 全プラグインの注入ルールを `${CLAUDE_PLUGIN_ROOT}/injection_rules.yaml` に集約
- ルール内のパスは `${plugin-name}/path/to/reference.md` 形式
- フックは `${plugin-name}` を実プラグインの `references/` ディレクトリに展開:
    1. ${CLAUDE_PROJECT_DIR}/plugins/{plugin}/references/  (marketplace 開発時)
    2. ${HOME}/.claude/plugins/cache/*/{plugin}/*/references/  (インストール済み)
    3. ${REFS_INJECT_KIT_EXTRA_PATHS} の各エントリ
- 各プラグインの `references/index.yaml` (または `index.jp.yaml`) から description を取得

同一ファイルへの 2 回目以降の編集は、セッション + ファイルハッシュ単位のトークンで
スキップする (1 セッション 1 ファイル 1 回だけブロック)。

依存:
    - PyYAML  (pip install pyyaml)
    - Jinja2  (pip install jinja2)
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import re
import sys
import tempfile


def _eprint(msg: str) -> None:
    """stderr に出力（フックの transcript に残り、Claude へは渡さない）。"""
    sys.stderr.write(f"[refs-inject-kit] {msg}\n")


def _plugin_root() -> pathlib.Path:
    """refs-inject-kit プラグインの root を返す。"""
    env = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        return pathlib.Path(env)
    return pathlib.Path(__file__).resolve().parents[1]


# --------------------------------------------------------------------------- #
# glob → regex  (** = 任意階層、* = 単一階層内、? = 1 文字)
# --------------------------------------------------------------------------- #
def _glob_to_regex(pattern: str) -> re.Pattern[str]:
    parts: list[str] = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "*" and i + 1 < len(pattern) and pattern[i + 1] == "*":
            parts.append(".*")
            i += 2
            if i < len(pattern) and pattern[i] == "/":
                i += 1
        elif c == "*":
            parts.append("[^/]*")
            i += 1
        elif c == "?":
            parts.append("[^/]")
            i += 1
        elif c in "[]":
            parts.append(c)
            i += 1
        elif c == "{":
            parts.append("(?:")
            i += 1
        elif c == "}":
            parts.append(")")
            i += 1
        elif c == ",":
            parts.append("|")
            i += 1
        else:
            parts.append(re.escape(c))
            i += 1
    return re.compile("^" + "".join(parts) + "$")


def _match_any(pattern: str, candidates: list[str]) -> bool:
    rx = _glob_to_regex(pattern)
    return any(rx.match(c) for c in candidates)


# --------------------------------------------------------------------------- #
# プラグイン解決: `${plugin-name}` → references ディレクトリの実パス
# --------------------------------------------------------------------------- #
_PLACEHOLDER = re.compile(r"^\$\{([^}]+)\}/(.+)$")


def _resolve_plugin_refs_dir(plugin_name: str) -> pathlib.Path | None:
    """プラグイン名から references/ の実パスを返す。"""
    # 1. ${CLAUDE_PROJECT_DIR}/plugins/{plugin}/references/  (marketplace dev)
    proj = os.environ.get("CLAUDE_PROJECT_DIR")
    if proj:
        candidate = pathlib.Path(proj) / "plugins" / plugin_name / "references"
        if candidate.is_dir():
            return candidate

    # 2. ${HOME}/.claude/plugins/cache/*/{plugin}/*/references/  (installed)
    cache = pathlib.Path.home() / ".claude" / "plugins" / "cache"
    if cache.exists():
        # 各 owner / 各バージョンを総当たり、最新優先
        matches = sorted(cache.glob(f"*/{plugin_name}/*/references"))
        if matches:
            return matches[-1]

    # 3. ${REFS_INJECT_KIT_EXTRA_PATHS}（各エントリは plugin root）
    extra = os.environ.get("REFS_INJECT_KIT_EXTRA_PATHS", "")
    for entry in extra.split(os.pathsep):
        entry = entry.strip()
        if not entry:
            continue
        candidate = pathlib.Path(entry) / "references"
        if candidate.is_dir() and candidate.parent.name == plugin_name:
            return candidate

    return None


def _parse_ref(ref: str) -> tuple[str, str] | None:
    """`${plugin}/path/to/ref.md` → (plugin, path) に分解。形式不一致なら None。"""
    m = _PLACEHOLDER.match(ref.strip())
    if not m:
        return None
    return m.group(1), m.group(2)


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main() -> int:
    # 依存チェック (失敗時は静かに pass)
    try:
        import yaml
        from jinja2 import Environment, FileSystemLoader, StrictUndefined
    except ImportError as e:
        _eprint(f"missing dependency: {e}. install with: pip install pyyaml jinja2")
        return 0

    try:
        data = json.loads(sys.stdin.read())
    except Exception as e:
        _eprint(f"stdin parse error: {e}")
        return 0

    tool_name = data.get("tool_name", "")
    if tool_name not in ("Edit", "Write", "MultiEdit"):
        return 0

    file_path: str = data.get("tool_input", {}).get("file_path", "") or ""
    if not file_path:
        return 0

    plugin_root = _plugin_root()
    rules_yaml = plugin_root / "injection_rules.yaml"
    if not rules_yaml.exists():
        _eprint(f"injection_rules.yaml not found at {rules_yaml}")
        return 0

    try:
        rules_doc = yaml.safe_load(rules_yaml.read_text(encoding="utf-8")) or {}
    except Exception as e:
        _eprint(f"injection_rules.yaml parse error: {e}")
        return 0
    rules = rules_doc.get("rules") or []

    # 言語選択 (デフォルト英語)
    lang = os.environ.get("REFS_INJECT_KIT_LANG", "en").lower()
    index_filename = "index.jp.yaml" if lang == "jp" else "index.yaml"
    template_filename = "injection.jp.md.j2" if lang == "jp" else "injection.md.j2"

    # ----- ファイルパスの候補 -----
    norm: list[str] = [file_path.replace("\\", "/")]
    project_dir = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    try:
        rel = pathlib.Path(file_path).resolve().relative_to(pathlib.Path(project_dir).resolve())
        norm.append(str(rel).replace("\\", "/"))
    except (ValueError, OSError):
        pass

    # ----- rules を照合して `${plugin}/path` を集める -----
    required_raw: list[str] = []
    optional_raw: list[str] = []
    for rule in rules:
        pat = rule.get("pattern", "")
        if not pat:
            continue
        if _match_any(pat, norm):
            required_raw.extend(rule.get("required") or [])
            optional_raw.extend(rule.get("optional") or [])

    def _dedup(xs: list[str]) -> list[str]:
        seen: set[str] = set()
        out: list[str] = []
        for x in xs:
            if x not in seen:
                seen.add(x)
                out.append(x)
        return out

    required_raw = _dedup(required_raw)
    optional_raw = _dedup([p for p in optional_raw if p not in set(required_raw)])
    if not required_raw and not optional_raw:
        return 0

    # ----- セッション + ファイル単位のトークン (1 ファイル 1 回だけ block) -----
    session_id: str = data.get("session_id", "default")
    file_hash = hashlib.sha1(file_path.encode("utf-8")).hexdigest()[:12]
    token = pathlib.Path(tempfile.gettempdir()) / f"refs-inject-kit-{session_id}-{file_hash}"
    if token.exists():
        return 0

    # ----- 各 `${plugin}/path` を解決して本文 + description を集める -----
    # plugin → refs_dir のキャッシュ
    plugin_dir_cache: dict[str, pathlib.Path | None] = {}
    # plugin → description マップのキャッシュ
    plugin_desc_cache: dict[str, dict[str, str]] = {}

    def _plugin_refs_dir(plugin: str) -> pathlib.Path | None:
        if plugin not in plugin_dir_cache:
            plugin_dir_cache[plugin] = _resolve_plugin_refs_dir(plugin)
        return plugin_dir_cache[plugin]

    def _plugin_descriptions(plugin: str) -> dict[str, str]:
        if plugin in plugin_desc_cache:
            return plugin_desc_cache[plugin]
        out: dict[str, str] = {}
        refs_dir = _plugin_refs_dir(plugin)
        if refs_dir:
            idx_yaml = refs_dir / index_filename
            if idx_yaml.exists():
                try:
                    idx_doc = yaml.safe_load(idx_yaml.read_text(encoding="utf-8")) or {}
                    for ref in idx_doc.get("references") or []:
                        p = ref.get("path")
                        d = ref.get("description") or ""
                        if p:
                            out[p] = d
                except Exception as e:
                    _eprint(f"{idx_yaml} parse error: {e}")
        plugin_desc_cache[plugin] = out
        return out

    def _resolve_one(raw: str) -> dict[str, str] | None:
        """`${plugin}/path/to/ref.md` を解決して本文 + description を返す。"""
        parsed = _parse_ref(raw)
        if not parsed:
            _eprint(f"invalid placeholder format (expected ${{plugin}}/path): {raw}")
            return None
        plugin, sub_path = parsed
        refs_dir = _plugin_refs_dir(plugin)
        if not refs_dir:
            _eprint(f"plugin '{plugin}' references/ not found anywhere")
            return None
        full = refs_dir / sub_path
        body = ""
        if full.exists():
            try:
                body = full.read_text(encoding="utf-8")
            except Exception as e:
                _eprint(f"read failed {full}: {e}")
        else:
            _eprint(f"reference not found: {full}")
        descriptions = _plugin_descriptions(plugin)
        return {
            "raw": raw,
            "plugin": plugin,
            "path": sub_path,
            "description": descriptions.get(sub_path, ""),
            "body": body,
        }

    required_data = [r for r in (_resolve_one(s) for s in required_raw) if r]
    optional_data = [r for r in (_resolve_one(s) for s in optional_raw) if r]

    if not required_data and not optional_data:
        # 解決失敗した場合はブロックしない
        return 0

    token.touch()

    # ----- Jinja2 render -----
    tmpl_dir = plugin_root / "hooks" / "templates"
    env = Environment(
        loader=FileSystemLoader(str(tmpl_dir)),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    try:
        tmpl = env.get_template(template_filename)
        reason = tmpl.render(
            file_path=file_path,
            required=required_data,
            optional=optional_data,
        )
    except Exception as e:
        _eprint(f"template render error ({template_filename}): {e}")
        lines = [f"# refs-inject-kit (template error: {e})", "", f"target: {file_path}", ""]
        for r in required_data:
            lines.append(f"## {r['raw']}")
            lines.append("")
            lines.append(r["body"])
            lines.append("")
        reason = "\n".join(lines)

    sys.stdout.buffer.write(
        json.dumps({"decision": "block", "reason": reason}, ensure_ascii=False).encode("utf-8")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
