# Generated by claude-kit/hook-creator v3.19.1
"""dev-kit / yaml-skill-dispatch — PreToolUse(Edit, Write) hook.

.yaml / .yml ファイルを編集・作成しようとしたとき、セッション初回のみ
dev-kit:yaml スキルの概要を Claude に注入する。

ループ防止: セッション単位フラグ（消去しない）を使い、1 セッション内では
初回のみブロック・以降は素通り。

Args:
    sys.argv[1]: プロンプト本文の Markdown ファイルパス
"""

from __future__ import annotations

import json
import pathlib
import sys
import tempfile


def main() -> None:
    payload = json.loads(sys.stdin.read())
    tool_input = payload.get("tool_input", {})
    file_path = tool_input.get("file_path", "") or ""

    if not (file_path.endswith(".yaml") or file_path.endswith(".yml")):
        return

    session_id = payload.get("session_id", "default")
    flag = pathlib.Path(tempfile.gettempdir()) / f"dev-kit-yaml-skill-{session_id}"

    if flag.exists():
        return

    flag.touch()

    prompt_path = pathlib.Path(sys.argv[1])
    if not prompt_path.exists():
        return

    response = {"decision": "block", "reason": prompt_path.read_text("utf-8")}
    sys.stdout.buffer.write(json.dumps(response, ensure_ascii=False).encode("utf-8"))


if __name__ == "__main__":
    main()
