# Generated by claude-kit/hook-creator v3.27.2
"""claude-kit creator-dispatch hook (session-flag block type).

PreToolUse(Edit | Write) で発火し、編集対象ファイルパスを下表の RULES と照合する。
マッチしたら対応する prompt ファイルの内容を `decision: block` の reason に注入し、
「直接編集する前に creator スキルを通せ」と Claude に促す。

セッションフラグ型ブロック: ルールごとに `/tmp/{name}-{session_id}` フラグを使い、
**1 セッション中そのルールにつき 1 回だけ** ブロックする。ユーザーが creator スキルを
経由したあと（= ブロック後の再編集）は同セッション内ではそのまま通す。

インライン `-c` ワンライナーから本スクリプトへ抽出した（PR153）。インライン python は
クォートのネストで壊れやすい（incident `statusline-python-quote-nesting` 参照）。

RULES の pattern は相互排他（SKILL.md / .claude/rules / CLAUDE.md / .j2）なので
最初にマッチした 1 件だけを処理する。
"""
from __future__ import annotations

import json
import pathlib
import re
import sys
import tempfile

# 各ルール: name=フラグ名, pattern=対象パスの正規表現,
# exclude_jp=*.jp.md を除外するか, prompt=注入する prompts/ 配下のファイル名
RULES: list[dict[str, object]] = [
    {
        "name": "skill-creator-dispatch",
        "pattern": r"/skills/[^/]+/SKILL(?:\.jp)?\.md$",
        "exclude_jp": False,
        "prompt": "skill-creator-dispatch.md",
    },
    {
        "name": "rule-creator-dispatch",
        "pattern": r"\.claude/rules/.*\.md$",
        "exclude_jp": True,
        "prompt": "rule-creator-dispatch.md",
    },
    {
        "name": "claude-creator-dispatch",
        "pattern": r"(?:^|/)CLAUDE(?:\.local)?\.md$",
        "exclude_jp": True,
        "prompt": "claude-creator-dispatch.md",
    },
    {
        "name": "j2-stamp-check",
        "pattern": r"\.j2$",
        "exclude_jp": False,
        "prompt": "j2-stamp-check.md",
    },
]


def _prompts_dir() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parent / "prompts"


def main() -> int:
    try:
        data = json.loads(sys.stdin.read())
    except Exception:
        return 0

    file_path = (data.get("tool_input", {}).get("file_path", "") or "").replace("\\", "/")
    if not file_path:
        return 0

    session_id = data.get("session_id", "default")

    for rule in RULES:
        if rule["exclude_jp"] and file_path.endswith(".jp.md"):
            continue
        if not re.search(str(rule["pattern"]), file_path):
            continue

        flag = pathlib.Path(tempfile.gettempdir()) / f"{rule['name']}-{session_id}"
        if flag.exists():
            return 0  # 同セッションで既にブロック済み → 通す
        flag.touch()

        prompt_file = _prompts_dir() / str(rule["prompt"])
        if not prompt_file.exists():
            return 0
        sys.stdout.buffer.write(
            json.dumps(
                {"decision": "block", "reason": prompt_file.read_text("utf-8")},
                ensure_ascii=False,
            ).encode("utf-8")
        )
        return 0

    return 0


if __name__ == "__main__":
    sys.exit(main())
