# Generated by claude-kit/hook-creator v3.30.0
"""claude-kit j2-stamp-check hook (session-flag block type).

PreToolUse(Edit | Write) で発火し、編集対象が `.j2`（Jinja2 テンプレート）なら
「ファイル冒頭に mark-generated スタンプがあるか確認せよ」と促す prompt を
`decision: block` の reason に注入する。

セッションフラグ型ブロック: `/tmp/j2-stamp-check-{session_id}` フラグを使い、
**1 セッション中 1 回だけ** ブロックする。確認後の再編集は同セッション内では通す。

PR159 までは汎用 creator_dispatch.py が複数ルール（skill/rule/claude/hook/plugin/j2）を
扱っていたが、creator 系ルールは ref-inject のリファレンス自動注入へ置き換わったため廃止し、
非 creator 系の j2-stamp-check だけをこの専用スクリプトに切り出した。
"""
from __future__ import annotations

import json
import pathlib
import sys
import tempfile


def _prompt_file() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parent / "prompts" / "j2-stamp-check.md"


def main() -> int:
    try:
        data = json.loads(sys.stdin.read())
    except Exception:
        return 0

    file_path = (data.get("tool_input", {}).get("file_path", "") or "").replace("\\", "/")
    if not file_path.endswith(".j2"):
        return 0

    session_id = data.get("session_id", "default")
    flag = pathlib.Path(tempfile.gettempdir()) / f"j2-stamp-check-{session_id}"
    if flag.exists():
        return 0  # 同セッションで既にブロック済み → 通す
    flag.touch()

    prompt_file = _prompt_file()
    if not prompt_file.exists():
        return 0
    sys.stdout.buffer.write(
        json.dumps(
            {"decision": "block", "reason": prompt_file.read_text("utf-8")},
            ensure_ascii=False,
        ).encode("utf-8")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
