# Generated by claude-kit/hook-creator v3.27.2
"""claude-kit JP ミラー作成確認フック (PostToolUse Write)。

Claude が管理する `.md` ファイル（SKILL.md / .claude/rules/*.md / hooks/prompts/*.md /
CLAUDE.md）が Write されたあとに発火し、対応する `.jp.md` ミラーがまだ無ければ
prompts/jp-mirror-check.md の内容を stdout に出して「同コミットで JP ミラーを作れ」と促す。

PostToolUse なのでブロックはしない（stdout 出力のみ）。インライン `-c` から抽出した（PR153）。
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

# JP ミラーが必要な .md パターン（英語原本のみ対象）
_PATTERNS = [
    r"/skills/[^/]+/SKILL\.md$",
    r"\.claude/rules/[^/]+\.md$",
    r"/hooks/prompts/[^/]+\.md$",
    r"(?:^|/)CLAUDE(?:\.local)?\.md$",
]


def _prompt_file() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parent / "prompts" / "jp-mirror-check.md"


def main() -> int:
    try:
        data = json.loads(sys.stdin.read())
    except Exception:
        return 0

    file_path = data.get("tool_input", {}).get("file_path", "") or ""
    if not file_path.endswith(".md") or file_path.endswith(".jp.md"):
        return 0
    if not any(re.search(p, file_path) for p in _PATTERNS):
        return 0

    if pathlib.Path(file_path[:-3] + ".jp.md").exists():
        return 0  # JP ミラーは既にある → 何もしない

    prompt = _prompt_file()
    if prompt.exists():
        sys.stdout.buffer.write(prompt.read_text("utf-8").encode("utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
