# Generated by ref-inject/apply — regenerate via /ref-inject:apply
"""__PLUGIN_NAME__ references auto-injection hook.

PreToolUse(Edit | Write | MultiEdit | Read) で発火し、対象ファイルパスを
references/injection_rules.yaml の rules と照合する。マッチしたパターンの
required reference は **本文全量** を、optional reference は **パス + description のみ** を
Jinja2 で整形して `decision: block` の reason に注入する。

注入の重複は「パターン単位の TTL トークン」で制御する:
    ~/.claude/tokens/__PLUGIN_NAME__/{session_id}.yaml
は pattern をキーにした YAML マップで、各エントリに expires_at (epoch 秒) を持つ。
expires_at は注入時に now + TTL で決まり、`now < expires_at` の間は再注入しない。
TTL はデフォルト __DEFAULT_TTL__ 秒、環境変数 __ENV_PREFIX___INJECTION_TTL (秒) で上書きできる。
フック発火のたびに全セッションのトークンを走査し、期限切れエントリ (now >= expires_at) を
削除する (空になったファイルは削除)。期限切れ後に再びマッチすれば再注入される。

description は references/index.yaml (英語) から path -> description として取得する。
環境変数 __ENV_PREFIX___INJECTION_LANG=jp で index.jp.yaml + injection.jp.md.j2 に切替。

依存:
    - PyYAML  (uv/pip install pyyaml)
    - Jinja2  (uv/pip install jinja2)
"""
from __future__ import annotations

import json
import os
import pathlib
import re
import sys
import time

PLUGIN_NAME = "__PLUGIN_NAME__"
ENV_PREFIX = "__ENV_PREFIX__"
LOG_TAG = "__LOG_TAG__"
DEFAULT_TTL = __DEFAULT_TTL__


def _eprint(msg: str) -> None:
    """stderr に出力（フックの transcript に残り、Claude へは渡さない）。"""
    sys.stderr.write(f"[{LOG_TAG}] {msg}\n")


def _plugin_root() -> pathlib.Path:
    """plugin ルートを返す。

    Claude Code は hook 起動時に CLAUDE_PLUGIN_ROOT を設定するが、
    フォールバックとしてスクリプト位置の 2 階層上 (hooks/ の親) を使う。
    """
    env = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        return pathlib.Path(env)
    return pathlib.Path(__file__).resolve().parents[1]


def _ttl() -> int:
    raw = os.environ.get(f"{ENV_PREFIX}_INJECTION_TTL")
    if raw:
        try:
            return max(0, int(raw))
        except ValueError:
            _eprint(f"invalid {ENV_PREFIX}_INJECTION_TTL={raw!r}, using default {DEFAULT_TTL}")
    return DEFAULT_TTL


# --------------------------------------------------------------------------- #
# glob -> regex  (** = 任意階層、* = 単一階層内、? = 1 文字)
# --------------------------------------------------------------------------- #
def _glob_to_regex(pattern: str) -> re.Pattern[str]:
    parts: list[str] = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "*" and i + 1 < len(pattern) and pattern[i + 1] == "*":
            parts.append(".*")
            i += 2
            if i < len(pattern) and pattern[i] == "/":
                i += 1
        elif c == "*":
            parts.append("[^/]*")
            i += 1
        elif c == "?":
            parts.append("[^/]")
            i += 1
        elif c in "[]":
            parts.append(c)
            i += 1
        elif c == "{":
            parts.append("(?:")
            i += 1
        elif c == "}":
            parts.append(")")
            i += 1
        elif c == ",":
            parts.append("|")
            i += 1
        else:
            parts.append(re.escape(c))
            i += 1
    return re.compile("^" + "".join(parts) + "$")


def _match_any(pattern: str, candidates: list[str]) -> bool:
    rx = _glob_to_regex(pattern)
    return any(rx.match(c) for c in candidates)


# --------------------------------------------------------------------------- #
# トークン (pattern をキーにしたセッション単位 YAML マップ)
# --------------------------------------------------------------------------- #
def _load_token(path: pathlib.Path, yaml) -> dict[str, dict]:
    if not path.exists():
        return {}
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception as e:
        _eprint(f"token parse error ({path.name}): {e}")
        return {}
    return data if isinstance(data, dict) else {}


def _save_token(path: pathlib.Path, data: dict[str, dict], yaml) -> None:
    try:
        path.write_text(yaml.safe_dump(data, allow_unicode=True, sort_keys=True), encoding="utf-8")
    except Exception as e:
        _eprint(f"token write error ({path.name}): {e}")


def _cleanup_expired(token_dir: pathlib.Path, now: float, yaml) -> None:
    """全セッションのトークンを走査し、期限切れエントリ (now >= expires_at) を削除する。

    空になったファイルは削除する。異常終了したセッションのトークンも
    期限切れ後にどこかでフックが発火した時点で自然に消える。
    """
    if not token_dir.exists():
        return
    for f in token_dir.glob("*.yaml"):
        data = _load_token(f, yaml)
        if not data:
            f.unlink(missing_ok=True)
            continue
        changed = False
        for key in list(data):
            entry = data.get(key) or {}
            exp = entry.get("expires_at") if isinstance(entry, dict) else None
            if not isinstance(exp, (int, float)) or now >= exp:
                del data[key]
                changed = True
        if not data:
            f.unlink(missing_ok=True)
        elif changed:
            _save_token(f, data, yaml)


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main() -> int:
    # 依存チェック (失敗時は静かに pass)
    try:
        import yaml
        from jinja2 import Environment, FileSystemLoader, StrictUndefined
    except ImportError as e:
        _eprint(f"missing dependency: {e}. install with: uv add --dev pyyaml jinja2")
        return 0

    try:
        data = json.loads(sys.stdin.read())
    except Exception as e:
        _eprint(f"stdin parse error: {e}")
        return 0

    tool_name = data.get("tool_name", "")
    if tool_name not in ("Edit", "Write", "MultiEdit", "Read"):
        return 0

    file_path: str = data.get("tool_input", {}).get("file_path", "") or ""
    if not file_path:
        return 0

    plugin_root = _plugin_root()
    refs_dir = plugin_root / "references"

    # 言語選択: 環境変数 __ENV_PREFIX___INJECTION_LANG=jp で日本語版
    lang = os.environ.get(f"{ENV_PREFIX}_INJECTION_LANG", "en").lower()
    index_filename = "index.jp.yaml" if lang == "jp" else "index.yaml"
    template_filename = "injection.jp.md.j2" if lang == "jp" else "injection.md.j2"

    rules_yaml = refs_dir / "injection_rules.yaml"
    index_yaml = refs_dir / index_filename
    if not rules_yaml.exists():
        _eprint(f"injection_rules.yaml not found at {rules_yaml}")
        return 0
    if not index_yaml.exists():
        _eprint(f"{index_filename} not found at {index_yaml}")
        return 0

    # ----- injection_rules.yaml をロード -----
    try:
        rules_doc = yaml.safe_load(rules_yaml.read_text(encoding="utf-8")) or {}
    except Exception as e:
        _eprint(f"injection_rules.yaml parse error: {e}")
        return 0
    rules = rules_doc.get("rules") or []

    # ----- index.yaml から path -> description -----
    descriptions: dict[str, str] = {}
    try:
        idx_doc = yaml.safe_load(index_yaml.read_text(encoding="utf-8")) or {}
        for ref in idx_doc.get("references") or []:
            p = ref.get("path")
            d = ref.get("description") or ""
            if p:
                descriptions[p] = d
    except Exception as e:
        _eprint(f"{index_filename} parse error: {e}")

    # ----- file_path の候補を作る (絶対パス + プロジェクトルートからの相対パス) -----
    norm: list[str] = [file_path.replace("\\", "/")]
    project_dir = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    try:
        rel = pathlib.Path(file_path).resolve().relative_to(pathlib.Path(project_dir).resolve())
        norm.append(str(rel).replace("\\", "/"))
    except (ValueError, OSError):
        pass

    def _dedup(xs: list[str]) -> list[str]:
        seen: set[str] = set()
        out: list[str] = []
        for x in xs:
            if x not in seen:
                seen.add(x)
                out.append(x)
        return out

    # ----- トークン: TTL 判定 + クリーンアップ -----
    session_id: str = data.get("session_id", "default")
    token_dir = pathlib.Path.home() / ".claude" / "tokens" / PLUGIN_NAME
    ttl = _ttl()
    now = time.time()
    _cleanup_expired(token_dir, now, yaml)

    token_path = token_dir / f"{session_id}.yaml"
    token_data = _load_token(token_path, yaml)

    # ----- injection_rules を照合し、未注入 or 期限切れパターンの reference を集める -----
    required: list[str] = []
    optional: list[str] = []
    patterns_to_mark: list[str] = []
    for rule in rules:
        pat = rule.get("pattern", "")
        if not pat or not _match_any(pat, norm):
            continue
        entry = token_data.get(pat) or {}
        exp = entry.get("expires_at") if isinstance(entry, dict) else None
        if isinstance(exp, (int, float)) and now < exp:
            continue  # まだ期限内 → 再注入しない
        patterns_to_mark.append(pat)
        required.extend(rule.get("required") or [])
        optional.extend(rule.get("optional") or [])

    required = _dedup(required)
    optional = _dedup([p for p in optional if p not in set(required)])

    if not required and not optional:
        return 0  # マッチ無し、または全マッチパターンが TTL 内

    # 注入するパターンの expires_at (= now + TTL) を更新して保存
    token_dir.mkdir(parents=True, exist_ok=True)
    for pat in patterns_to_mark:
        token_data[pat] = {"expires_at": int(now) + ttl}
    _save_token(token_path, token_data, yaml)

    # ----- required = 本文全量 / optional = パス + description -----
    # 注入テキスト内では ${CLAUDE_PLUGIN_ROOT} は展開されないため絶対パスを出す。
    def _required_ref(rel_path: str) -> dict[str, str]:
        p = refs_dir / rel_path
        try:
            body = p.read_text(encoding="utf-8")
        except Exception as e:
            _eprint(f"reference read error ({rel_path}): {e}")
            body = ""
        return {
            "path": rel_path,
            "abs_path": p.as_posix(),
            "description": descriptions.get(rel_path, ""),
            "body": body,
        }

    def _optional_ref(rel_path: str) -> dict[str, str]:
        return {
            "path": rel_path,
            "abs_path": (refs_dir / rel_path).as_posix(),
            "description": descriptions.get(rel_path, ""),
        }

    required_data = [_required_ref(p) for p in required]
    optional_data = [_optional_ref(p) for p in optional]

    # ----- Jinja2 render -----
    tmpl_dir = plugin_root / "hooks" / "templates"
    env = Environment(
        loader=FileSystemLoader(str(tmpl_dir)),
        undefined=StrictUndefined,
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    try:
        tmpl = env.get_template(template_filename)
        reason = tmpl.render(
            file_path=file_path,
            required=required_data,
            optional=optional_data,
        )
    except Exception as e:
        _eprint(f"template render error ({template_filename}): {e}")
        lines = [f"# {PLUGIN_NAME} references (template error: {e})", "", f"target: {file_path}", ""]
        for r in required_data:
            lines.append(f"## {r['abs_path']} — {r['description']}")
            lines.append(r["body"])
        reason = "\n".join(lines)

    sys.stdout.buffer.write(
        json.dumps({"decision": "block", "reason": reason}, ensure_ascii=False).encode("utf-8")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
