# Generated by ref-inject/create — regenerate via /ref-inject:create
"""__PLUGIN_NAME__ injection-token refresh on /compact.

PreCompact で発火し、このセッションの注入トークン
    ~/.claude/tokens/__PLUGIN_NAME__/{session_id}.yaml
を削除する。/compact でコンテキストが圧縮されると注入済みの reference 本文が
失われるため、トークンを消して次の Edit/Write/Read で全パターンを再注入させる。

何も出力しない (decision を返さない) ので作業フローは止めない。
"""
from __future__ import annotations

import json
import pathlib
import sys

PLUGIN_NAME = "__PLUGIN_NAME__"


def main() -> int:
    try:
        data = json.loads(sys.stdin.read())
    except Exception:
        return 0

    session_id = data.get("session_id", "")
    if not session_id:
        return 0

    token_path = pathlib.Path.home() / ".claude" / "tokens" / PLUGIN_NAME / f"{session_id}.yaml"
    try:
        token_path.unlink(missing_ok=True)
    except OSError:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
