# Generated by claude-kit/hook-creator v3.17.0
"""ui-kit / user-prompt-submit — UserPromptSubmit hook.

HTML/CSS/JS の実装・編集が検出された場合に implement / logging スキルの
起動リマインダーを注入する。モック作成が要求された場合は mock スキルも追加する。

Args:
    sys.argv[1]: prompts/ ディレクトリパス
                 (hooks.json から `${CLAUDE_PLUGIN_ROOT}/hooks/prompts` を渡す)
"""

from __future__ import annotations

import json
import pathlib
import sys

UI_KEYWORDS = [
    "html", "css", "javascript", " js ", ".js", ".ts", "typescript",
    "フロントエンド", "実装", "スタイル", "コンポーネント",
    "implement", "frontend", "style", "component", "uidev",
    "ui ", "画面", "レイアウト",
]

MOCK_KEYWORDS = [
    "mock", "モック", "モックアップ", "mockup",
]


def main() -> None:
    data = json.loads(sys.stdin.read())
    prompt = data.get("prompt", "").lower()

    is_ui = any(kw in prompt for kw in UI_KEYWORDS)
    is_mock = any(kw in prompt for kw in MOCK_KEYWORDS)

    if not is_ui and not is_mock:
        return

    prompts_dir = pathlib.Path(sys.argv[1])
    filename = "with-mock.md" if is_mock else "base.md"
    prompt_file = prompts_dir / filename

    if prompt_file.exists():
        sys.stdout.buffer.write(prompt_file.read_bytes())


if __name__ == "__main__":
    main()
