#!/usr/bin/env bash
# gh-kit ラベル名定義。SKILL/agent 先頭で `!\`cat\`` 展開して読み込む。
# すべての gh-kit フロー専用ラベルは "gh-kit:" プレフィックス付き。

LABEL_PROCESSING="gh-kit:processing"
LABEL_NEEDS_AI_REVIEW="gh-kit:needs-ai-review"
LABEL_NEEDS_USER_REVIEW="gh-kit:needs-user-review"
LABEL_NEEDS_FIX="gh-kit:needs-fix"
LABEL_AI_CODE_SCAN="gh-kit:ai-code-scan"
LABEL_WIP="gh-kit:wip"
LABEL_PROCESSING_PR_DRAFT="processing:pr-draft"
LABEL_PROCESSING_PR_IMPLEMENT="processing:pr-implement"
LABEL_PROCESSING_PR_REVIEW="processing:pr-review"

LABEL_COLOR_PROCESSING="FBCA04"
LABEL_COLOR_NEEDS_AI_REVIEW="0E8A16"
LABEL_COLOR_NEEDS_USER_REVIEW="C5DEF5"
LABEL_COLOR_NEEDS_FIX="D93F0B"
LABEL_COLOR_AI_CODE_SCAN="1D76DB"
LABEL_COLOR_WIP="C2E0C6"
LABEL_COLOR_PROCESSING_PR_DRAFT="FBCA04"
LABEL_COLOR_PROCESSING_PR_IMPLEMENT="FBCA04"
LABEL_COLOR_PROCESSING_PR_REVIEW="FBCA04"

LABEL_PRIORITY_HIGH="priority:high"
LABEL_PRIORITY_MEDIUM="priority:medium"
LABEL_PRIORITY_LOW="priority:low"

LABEL_COLOR_PRIORITY_HIGH="B60205"
LABEL_COLOR_PRIORITY_MEDIUM="E4E669"
LABEL_COLOR_PRIORITY_LOW="0075CA"
