#!/usr/bin/env bash
# gh-kit ラベル名定義。SKILL/agent 先頭で `!\`cat\`` 展開して読み込む。

LABEL_PROCESSING="processing"
LABEL_NEEDS_AI_REVIEW="needs-ai-review"
LABEL_NEEDS_USER_REVIEW="needs-user-review"
LABEL_NEEDS_FIX="needs-fix"
LABEL_AI_CODE_SCAN="ai-code-scan"
LABEL_WIP="wip"
LABEL_PROCESSING_PR_DRAFT="processing:pr-draft"
LABEL_PROCESSING_PR_IMPLEMENT="processing:pr-implement"
LABEL_PROCESSING_PR_REVIEW="processing:pr-review"

LABEL_COLOR_PROCESSING="FBCA04"
LABEL_COLOR_NEEDS_AI_REVIEW="0E8A16"
LABEL_COLOR_NEEDS_USER_REVIEW="C5DEF5"
LABEL_COLOR_NEEDS_FIX="D93F0B"
LABEL_COLOR_AI_CODE_SCAN="1D76DB"
LABEL_COLOR_WIP="C2E0C6"
LABEL_COLOR_PROCESSING_PR_DRAFT="FBCA04"
LABEL_COLOR_PROCESSING_PR_IMPLEMENT="FBCA04"
LABEL_COLOR_PROCESSING_PR_REVIEW="FBCA04"
